obstacle_range: 1.5
raytrace_range: 3.0
footprint: [ [0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3] ]

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lens_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
