global_costmap:
  global_frame: odom
  robot_base_frame: base_generic_link
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: false
  rolling_window: true
  width: 100.0
  height: 100.0
  resolution: 0.05
  inflation_radius: 1
